name: AI Infra Tools - DockerHub Matrix Build
description: |
  This workflow builds and pushes Docker images to DockerHub for multiple AI Infra Tools.
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: aiinfra-tools
  PLATFORMS: linux/amd64

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - file: Dockerfile.mini
            tag: mini
          - file: Dockerfile.oci
            tag: oci
          - file: Dockerfile.terraform
            tag: terraform
            
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/aiinfra-tools
        tags: |
          type=raw,value=${{ matrix.tag }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./${{ matrix.file }}
        platforms: ${{ env.PLATFORMS }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/aiinfra-tools:${{ matrix.tag }}
        cache-to: type=inline