name: Build & Push Multiple Docker Images Sequentially

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout source
        uses: actions/checkout@v4 #v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: leoustc/aiinfra-tools     # Change to your repo (e.g., leoustc/k8s etc as needed)
          readme-filepath: ./README.md

      - name: Build mini image
        run: |
          docker build -t docker.io/leoustc/aiinfra-tools:mini -f Dockerfile.mini .

      - name: Push mini image
        run: |
          docker push docker.io/leoustc/aiinfra-tools:mini

      - name: Build oci image
        run: |
          docker build -t docker.io/leoustc/aiinfra-tools:oci -f Dockerfile.oci .

      - name: Push oci image
        run: |
          docker push docker.io/leoustc/aiinfra-tools:oci

      - name: Build terraform image
        run: |
          docker build -t docker.io/leoustc/aiinfra-tools:terraform -f Dockerfile.terraform .

      - name: Push terraform image
        run: |
          docker push docker.io/leoustc/aiinfra-tools:terraform

      - name: Build k8s image and Push the image
        run: |
          docker build -t docker.io/leoustc/aiinfra-tools:k8s -f Dockerfile.k8s . && docker push docker.io/leoustc/aiinfra-tools:k8s
